### PR TITLE
Add FAQ about GUI

### PR DESCRIPTION
**Pull request by dtch1997**
Information obtained from https://github.com/deepmind/mujoco_mpc/issues/46

### CODE REVIEW

**Comment by thowell** [comment]
This is great, thanks for submitting!

Instead of adding this content to FAQ.md, can you add it to GUI.md?

**Comment by yuvaltassa** [comment]
I agree with Taylor on this, though perhaps GUI.md should be linked to more prominently in the README?

**Comment by dtch1997** [comment]
I agree! Having `GUI.md` featured more prominently in the README would definitely be helpful to new users. Will commit a suggestion on how this might be done

**Review by thowell — CHANGES_REQUESTED** [review]
Looks great!

Can you add the +/- keys to the simulate shortcuts?
    - `+` reduces simulation slowdown 
    - `-` increases simulation slowdown

**Review by yuvaltassa — APPROVED** [review]

**Review by thowell — APPROVED** [review]
LGTM

**Pull request merged**
